"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - lf_haa_joint
          - lf_hfe_joint
          - lf_kfe_joint
          - rf_haa_joint
          - rf_hfe_joint
          - rf_kfe_joint
          - lh_haa_joint
          - lh_hfe_joint
          - lh_kfe_joint
          - rh_haa_joint
          - rh_hfe_joint
          - rh_kfe_joint

      gains:
        lf_haa_joint : {p: 180, d: 0.9, i: 20}
        lf_hfe_joint : {p: 180, d: 0.9, i: 20}
        lf_kfe_joint : {p: 180, d: 0.9, i: 20}
        rf_haa_joint : {p: 180, d: 0.9, i: 20}
        rf_hfe_joint : {p: 180, d: 0.9, i: 20}
        rf_kfe_joint : {p: 180, d: 0.9, i: 20}
        lh_haa_joint : {p: 180, d: 0.9, i: 20}
        lh_hfe_joint : {p: 180, d: 0.9, i: 20}
        lh_kfe_joint : {p: 180, d: 0.9, i: 20}
        rh_haa_joint : {p: 180, d: 0.9, i: 20}
        rh_hfe_joint : {p: 180, d: 0.9, i: 20}
        rh_kfe_joint : {p: 180, d: 0.9, i: 20}
