<?xml version="1.0" ?>
<robot name="spot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- This argument allows us to load joint sensors that measure the internal wrenches -->
    <xacro:arg name="load_force_sensors" default="false"/>
    <xacro:arg name="sensors" default="false"/>
    <xacro:arg name="task_period" default="0.004"/>
    <xacro:arg name="arm_enabled" default="false"/>
    <xacro:arg name="arm_name" default="kinova"/>
    <xacro:arg name="floating_base_link" default="true"/>
    <xacro:arg name="robot_name"  default="spot"/>
    <xacro:arg name="base_name"   default="base_link"/>

    <!-- load generic materials -->
    <xacro:include filename="$(find wolf_description_utils)/urdfs/materials.xacro"/>

    <!-- generic simulator_gazebo plugins for starting mechanism control, ros time -->
    <xacro:include filename="$(find wolf_description_utils)/urdfs/gazebo.urdf.xacro"/>

    <!-- legs transmission and gazebo plugins -->
    <xacro:include filename="$(find wolf_description_utils)/urdfs/leg.transmission.xacro"/>
    <xacro:include filename="$(find wolf_description_utils)/urdfs/leg.gazebo.xacro"/>

    <!-- sensors -->
    <xacro:if value="$(arg sensors)">
        <xacro:include filename="$(find sensors_description)/urdfs/sensors/imu.gazebo.xacro"/>
    </xacro:if>

    <!-- dynamics inertial value -->
    <!-- body -->
    <xacro:property name="body_mass" value="11.041"/>
    <xacro:property name="body_com_x" value="0.008465"/>
    <xacro:property name="body_com_y" value="0.004045"/>
    <xacro:property name="body_com_z" value="-0.000763"/>
    <xacro:property name="body_ixx" value="0.050874"/>
    <xacro:property name="body_ixy" value="-0.000451628"/>
    <xacro:property name="body_ixz" value="0.000487603"/>
    <xacro:property name="body_iyy" value="0.64036"/>
    <xacro:property name="body_iyz" value="0.000048356"/>
    <xacro:property name="body_izz" value="0.65655"/>

    <!-- hip (left front) -->
    <xacro:property name="hip_mass" value="1.993"/>
    <xacro:property name="hip_com_x" value="-0.022191"/>
    <xacro:property name="hip_com_y" value="0.015144"/>
    <xacro:property name="hip_com_z" value="-0.000015"/>
    <xacro:property name="hip_ixx" value="0.002903894"/>
    <xacro:property name="hip_ixy" value="-0.000071850"/>
    <xacro:property name="hip_ixz" value="-0.000001262"/>
    <xacro:property name="hip_iyy" value="0.004907517"/>
    <xacro:property name="hip_iyz" value="-0.00000175"/>
    <xacro:property name="hip_izz" value="0.005586944"/>

    <!-- upperleg -->
    <xacro:property name="upperleg_mass" value="0.639"/>
    <xacro:property name="upperleg_com_x" value="-0.005607"/>
    <xacro:property name="upperleg_com_y" value="-0.003877"/>
    <xacro:property name="upperleg_com_z" value="-0.048199"/>
    <xacro:property name="upperleg_ixx" value="0.005666803"/>
    <xacro:property name="upperleg_ixy" value="0.000003597"/>
    <xacro:property name="upperleg_ixz" value="0.000491446"/>
    <xacro:property name="upperleg_iyy" value="0.005847229"/>
    <xacro:property name="upperleg_iyz" value="0.000010086"/>
    <xacro:property name="upperleg_izz" value="0.000369811"/>

    <!-- lowerleg -->
    <xacro:property name="lowerleg_mass" value="0.207"/>
    <xacro:property name="lowerleg_com_x" value="0.002781"/>
    <xacro:property name="lowerleg_com_y" value="0.000063"/>
    <xacro:property name="lowerleg_com_z" value="-0.142518"/>
    <xacro:property name="lowerleg_ixx" value="0.006341369"/>
    <xacro:property name="lowerleg_ixy" value="-0.000000003"/>
    <xacro:property name="lowerleg_ixz" value="-0.000087951"/>
    <xacro:property name="lowerleg_iyy" value="0.006355157"/>
    <xacro:property name="lowerleg_iyz" value="-0.000001336"/>
    <xacro:property name="lowerleg_izz" value="0.000039188"/>

    <!-- foot -->
    <xacro:property name="foot_mass" value="0.06"/>
    <xacro:property name="foot_radius" value="0.03"/>
    <xacro:property name="foot_x" value="-0.005"/>
    <xacro:property name="foot_z" value="-0.348"/>

    <!-- Floating-base Joint -->
    <xacro:if value="$(arg floating_base_link)">
        <link name="world"/>
        <joint name="floating_base_joint" type="floating">
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <parent link="world"/>
          <child link="base_link"/>
        </joint>
    </xacro:if>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="trunk_imu"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>
    <link name="trunk_imu"/>

    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/body.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/body_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${body_com_x} ${body_com_y} ${body_com_z}"/>
            <mass value="${body_mass}"/>
            <inertia
                ixx="${body_ixx}" ixy="${body_ixy}" ixz="${body_ixz}"
                iyy="${body_iyy}" iyz="${body_iyz}"
                izz="${body_izz}"/>
        </inertial>
    </link>

    <link name="front_rail"/>
    <joint name="front_rail_joint" type="fixed">
        <origin xyz="0.223 0 0.0805" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="front_rail" />
    </joint>

    <link name="rear_rail"/>
    <joint name="rear_rail_joint" type="fixed">
        <origin xyz="-0.223 0 0.0805" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="rear_rail" />
    </joint>

    <link name="lf_hip">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_hip.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_hip_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${hip_com_x*1} ${hip_com_y*1} ${hip_com_z}"/>
            <mass value="${hip_mass}"/>
            <inertia
                ixx="${hip_ixx}" ixy="${hip_ixy*1*1}" ixz="${hip_ixz*1}"
                iyy="${hip_iyy}" iyz="${hip_iyz*1}"
                izz="${hip_izz}"/>
        </inertial>
    </link>
    <joint name="lf_haa_joint" type="revolute">
        <origin xyz="0.29785 0.05500 0.00000" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="base_link" />
        <child link="lf_hip" />
        <limit effort="50" velocity="10" lower="-0.78539816339744827899" upper="0.78539816339744827899" />
    </joint>
    <link name="lf_upperleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_upper_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_upper_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${upperleg_com_x} ${upperleg_com_y*1} ${upperleg_com_z}"/>
            <mass value="${upperleg_mass}"/>
            <inertia
                ixx="${upperleg_ixx}" ixy="${upperleg_ixy*1}" ixz="${upperleg_ixz}"
                iyy="${upperleg_iyy}" iyz="${upperleg_iyz*1}"
                izz="${upperleg_izz}"/>
        </inertial>
    </link>
    <joint name="lf_hfe_joint" type="revolute">
        <origin xyz="0.0 0.110945 0.0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="lf_hip" />
        <child link="lf_upperleg" />
        <limit effort="50" velocity="10" lower="-0.89884456477707963539" upper="2.2951079663725435509" />
    </joint>
    <link name="lf_lowerleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_lower_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_left_lower_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${lowerleg_com_x} ${lowerleg_com_y*1} ${lowerleg_com_z}"/>
            <mass value="${lowerleg_mass}"/>
            <inertia
                ixx="${lowerleg_ixx}" ixy="${lowerleg_ixy*1}" ixz="${lowerleg_ixz}"
                iyy="${lowerleg_iyy}" iyz="${lowerleg_iyz*1}"
                izz="${lowerleg_izz}"/>
        </inertial>
    </link>
    <joint name="lf_kfe_joint" type="revolute">
        <origin xyz="0.025 0.000 -0.3205" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="lf_upperleg" />
        <child link="lf_lowerleg" />
        <limit effort="50" velocity="10" lower="-2.7929" upper="-0.254801" />
    </joint>
    <joint name="lf_foot_joint" type="fixed">
        <origin xyz="${foot_x} 0.0 ${foot_z}" rpy="0 0 0" />
        <parent link="lf_lowerleg" />
        <child link="lf_foot" />
    </joint>
    <link name="lf_foot">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${foot_radius-0.01}"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>
    </visual>
    <inertial>
        <mass value="${foot_mass}"/>
        <inertia
            ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
            iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
            izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
    </inertial>
    </link>

    <link name="rf_hip">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_hip.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_hip_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${hip_com_x*1} ${hip_com_y*-1} ${hip_com_z}"/>
            <mass value="${hip_mass}"/>
          <inertia
              ixx="${hip_ixx}" ixy="${hip_ixy*-1*1}" ixz="${hip_ixz*1}"
              iyy="${hip_iyy}" iyz="${hip_iyz*-1}"
              izz="${hip_izz}"/>
      </inertial>
    </link>
    <joint name="rf_haa_joint" type="revolute">
        <origin xyz="0.29785 -0.05500 0.00000" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="base_link" />
        <child link="rf_hip" />
        <limit effort="50" velocity="10" lower="-0.78539816339744827899" upper="0.78539816339744827899" />
    </joint>
    <link name="rf_upperleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_upper_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_upper_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${upperleg_com_x} ${upperleg_com_y*-1} ${upperleg_com_z}"/>
            <mass value="${upperleg_mass}"/>
            <inertia
                ixx="${upperleg_ixx}" ixy="${upperleg_ixy*-1}" ixz="${upperleg_ixz}"
                iyy="${upperleg_iyy}" iyz="${upperleg_iyz*-1}"
                izz="${upperleg_izz}"/>
        </inertial>
    </link>
    <joint name="rf_hfe_joint" type="revolute">
        <origin xyz="0.0 -0.110945 0.0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="rf_hip" />
        <child link="rf_upperleg" />
        <limit effort="50" velocity="10" lower="-0.89884456477707963539" upper="2.2951079663725435509" />
    </joint>
    <link name="rf_lowerleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_lower_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/front_right_lower_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${lowerleg_com_x} ${lowerleg_com_y*-1} ${lowerleg_com_z}"/>
            <mass value="${lowerleg_mass}"/>
            <inertia
                ixx="${lowerleg_ixx}" ixy="${lowerleg_ixy*-1}" ixz="${lowerleg_ixz}"
                iyy="${lowerleg_iyy}" iyz="${lowerleg_iyz*-1}"
                izz="${lowerleg_izz}"/>
        </inertial>
    </link>
    <joint name="rf_kfe_joint" type="revolute">
        <origin xyz="0.025 0.000 -0.3205" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="rf_upperleg" />
        <child link="rf_lowerleg" />
        <limit effort="50" velocity="10" lower="-2.7929" upper="-0.247563" />
    </joint>
    <joint name="rf_foot_joint" type="fixed">
        <origin xyz="${foot_x} 0.0 ${foot_z}" rpy="0 0 0" />
        <parent link="rf_lowerleg" />
        <child link="rf_foot" />
    </joint>
    <link name="rf_foot">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${foot_radius-0.01}"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>
    </visual>
    <inertial>
        <mass value="${foot_mass}"/>
        <inertia
            ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
            iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
            izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
    </inertial>
    </link>

    <link name="lh_hip">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_hip.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_hip_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${hip_com_x*-1} ${hip_com_y*1} ${hip_com_z}"/>
            <mass value="${hip_mass}"/>
            <inertia
                ixx="${hip_ixx}" ixy="${hip_ixy*1*-1}" ixz="${hip_ixz*-1}"
                iyy="${hip_iyy}" iyz="${hip_iyz*1}"
                izz="${hip_izz}"/>
        </inertial>
    </link>
    <joint name="lh_haa_joint" type="revolute">
        <origin xyz="-0.29785 0.05500 0.00000" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="base_link" />
        <child link="lh_hip" />
        <limit effort="50" velocity="10" lower="-0.78539816339744827899" upper="0.78539816339744827899" />
    </joint>
    <link name="lh_upperleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_upper_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_upper_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${upperleg_com_x} ${upperleg_com_y*1} ${upperleg_com_z}"/>
            <mass value="${upperleg_mass}"/>
            <inertia
                ixx="${upperleg_ixx}" ixy="${upperleg_ixy*1}" ixz="${upperleg_ixz}"
                iyy="${upperleg_iyy}" iyz="${upperleg_iyz*1}"
                izz="${upperleg_izz}"/>
        </inertial>
    </link>
    <joint name="lh_hfe_joint" type="revolute">
        <origin xyz="0.0 0.110945 0.0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="lh_hip" />
        <child link="lh_upperleg" />
        <limit effort="50" velocity="10" lower="-0.89884456477707963539" upper="2.2951079663725435509" />
    </joint>
    <link name="lh_lowerleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_lower_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_left_lower_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${lowerleg_com_x} ${lowerleg_com_y*1} ${lowerleg_com_z}"/>
            <mass value="${lowerleg_mass}"/>
            <inertia
                ixx="${lowerleg_ixx}" ixy="${lowerleg_ixy*1}" ixz="${lowerleg_ixz}"
                iyy="${lowerleg_iyy}" iyz="${lowerleg_iyz*1}"
                izz="${lowerleg_izz}"/>
        </inertial>
    </link>
    <joint name="lh_kfe_joint" type="revolute">
        <origin xyz="0.025 0.000 -0.3205" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="lh_upperleg" />
        <child link="lh_lowerleg" />
        <limit effort="50" velocity="10" lower="-2.7929" upper="-0.267153" />
    </joint>
    <joint name="lh_foot_joint" type="fixed">
        <origin xyz="${foot_x} 0.0 ${foot_z}" rpy="0 0 0" />
        <parent link="lh_lowerleg" />
        <child link="lh_foot" />
    </joint>
    <link name="lh_foot">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${foot_radius-0.01}"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>
    </visual>
    <inertial>
        <mass value="${foot_mass}"/>
        <inertia
            ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
            iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
            izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
    </inertial>
    </link>

    <link name="rh_hip">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_hip.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_hip_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${hip_com_x*-1} ${hip_com_y*-1} ${hip_com_z}"/>
            <mass value="${hip_mass}"/>
            <inertia
                ixx="${hip_ixx}" ixy="${hip_ixy*-1*-1}" ixz="${hip_ixz*-1}"
                iyy="${hip_iyy}" iyz="${hip_iyz*-1}"
                izz="${hip_izz}"/>
        </inertial>
    </link>
    <joint name="rh_haa_joint" type="revolute">
        <origin xyz="-0.29785 -0.05500 0.00000" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="base_link" />
        <child link="rh_hip" />
        <limit effort="50" velocity="10" lower="-0.78539816339744827899" upper="0.78539816339744827899" />
    </joint>
    <link name="rh_upperleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_upper_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_upper_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${upperleg_com_x} ${upperleg_com_y*-1} ${upperleg_com_z}"/>
            <mass value="${upperleg_mass}"/>
            <inertia
                ixx="${upperleg_ixx}" ixy="${upperleg_ixy*-1}" ixz="${upperleg_ixz}"
                iyy="${upperleg_iyy}" iyz="${upperleg_iyz*-1}"
                izz="${upperleg_izz}"/>
        </inertial>
    </link>
    <joint name="rh_hfe_joint" type="revolute">
        <origin xyz="0.0 -0.110945 0.0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="rh_hip" />
        <child link="rh_upperleg" />
        <limit effort="50" velocity="10" lower="-0.89884456477707963539" upper="2.2951079663725435509" />
    </joint>
    <link name="rh_lowerleg">
        <visual>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_lower_leg.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://spot_description/meshes/rear_right_lower_leg_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${lowerleg_com_x} ${lowerleg_com_y*-1} ${lowerleg_com_z}"/>
            <mass value="${lowerleg_mass}"/>
            <inertia
                ixx="${lowerleg_ixx}" ixy="${lowerleg_ixy*-1}" ixz="${lowerleg_ixz}"
                iyy="${lowerleg_iyy}" iyz="${lowerleg_iyz*-1}"
                izz="${lowerleg_izz}"/>
        </inertial>
    </link>
    <joint name="rh_kfe_joint" type="revolute">
        <origin xyz="0.025 0.000 -0.3205" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent link="rh_upperleg" />
        <child link="rh_lowerleg" />
        <limit effort="50" velocity="10" lower="-2.7929" upper="-0.257725" />
    </joint>
    <joint name="rh_foot_joint" type="fixed">
        <origin xyz="${foot_x} 0.0 ${foot_z}" rpy="0 0 0" />
        <parent link="rh_lowerleg" />
        <child link="rh_foot" />
    </joint>
    <link name="rh_foot">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${foot_radius-0.01}"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>
    </visual>
    <inertial>
        <mass value="${foot_mass}"/>
        <inertia
            ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
            iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
            izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
    </inertial>
    </link>

    <!-- Standard accessories. -->
    <xacro:if value="$(arg sensors)">
        <xacro:include filename="$(find spot_description)/urdfs/accessories.urdf.xacro" />
        <xacro:imu_sensor
            imu_name="trunk_imu"
            imu_topic="trunk_imu/data"
            update_rate="${1.0 / $(arg task_period)}"
            rate_mean="0"
            rate_stddev="0"
            rate_bias_mean="0"
            rate_bias_stddev="0"
            accel_mean="0"
            accel_stddev="0"
            accel_bias_mean="0"
            accel_bias_stddev="0">
        </xacro:imu_sensor>
    </xacro:if>

    <!-- Extensions -->
    <xacro:leg_transmission prefix="rf"/>
    <xacro:leg_gazebo prefix="rf" robot_name="$(arg robot_name)" load_force_sensors="$(arg load_force_sensors)"/>
    <xacro:leg_transmission prefix="lf"/>
    <xacro:leg_gazebo prefix="lf" robot_name="$(arg robot_name)" load_force_sensors="$(arg load_force_sensors)"/>
    <xacro:leg_transmission prefix="rh"/>
    <xacro:leg_gazebo prefix="rh" robot_name="$(arg robot_name)" load_force_sensors="$(arg load_force_sensors)"/>
    <xacro:leg_transmission prefix="lh"/>
    <xacro:leg_gazebo prefix="lh" robot_name="$(arg robot_name)" load_force_sensors="$(arg load_force_sensors)"/>

    <xacro:if value="$(arg arm_enabled)">
           <xacro:include filename="$(find spot_description)/urdfs/arm/$(arg arm_name)_adapter.urdf.xacro" /> -->
    </xacro:if>

</robot>
